language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  - BUILD=false TEST_COMMAND="node ./node_modules/lodash/test/test.js ./compat/lodash.js"
  - BUILD=false TEST_COMMAND="node ./node_modules/lodash/test/test.js ./modern/lodash.js"
  - BUILD="legacy" TEST_COMMAND="node ./node_modules/lodash/test/test.js ./legacy/lodash.js"
  - BUILD="mobile" TEST_COMMAND="node ./node_modules/lodash/test/test.js ./mobile/lodash.js"
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $BUILD != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $BUILD != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $BUILD == 'legacy' ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./legacy || true"
  - "[ $BUILD == 'mobile' ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./mobile || true"
  - $TEST_COMMAND
