language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - BIN="node" BASE_PATH="." EXPORTS="node" MAKE=false OPTION=""
  matrix:
    - BUILD="compat"
    - BUILD="modern"
    - BUILD="legacy" MAKE=true
    - BUILD="mobile" MAKE=true
    - BUILD="compat" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="legacy" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="mobile" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="modern" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
matrix:
  include:
    - node_js: "0.10"
      env: BIN="narwhal" BUILD="compat" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - node_js: "0.10"
      env: BIN="narwhal" BUILD="legacy" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - node_js: "0.10"
      env: BIN="ringo"   BUILD="compat" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - node_js: "0.10"
      env: BIN="ringo"   BUILD="legacy" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "[ $BIN == 'narwhal' ] && wget https://github.com/280north/narwhal/archive/v0.3.2.zip && sudo unzip v0.3.2 -d /opt/ && rm v0.3.2.zip || true"
  - "[ $BIN == 'narwhal' ] && sudo ln -s /opt/narwhal-0.3.2/bin/narwhal /usr/local/bin/narwhal && sudo chmod +x /usr/local/bin/narwhal || true"
  - "[ $BIN == 'ringo' ] && wget http://ringojs.org/downloads/ringojs-0.9.zip && sudo unzip ringojs-0.9 -d /opt && rm ringojs-0.9.zip || true"
  - "[ $BIN == 'ringo' ] && sudo ln -s /opt/ringojs-0.9/bin/ringo /usr/local/bin/ringo && sudo chmod +x /usr/local/bin/ringo || true"
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $MAKE != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize $BUILD exports=$EXPORTS -o $BASE_PATH/$BUILD || true"
  - "$BIN $OPTION ./node_modules/lodash/test/test.js ../../.$BASE_PATH/$BUILD/index.js"
