language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  - BUILD=false    EXPORTS="node"     BASE_PATH="."          TEST_COMMAND="node ./node_modules/lodash/test/test.js ./compat/lodash.js"
  - BUILD=false    EXPORTS="node"     BASE_PATH="."          TEST_COMMAND="node ./node_modules/lodash/test/test.js ./modern/lodash.js"
  - BUILD="legacy" EXPORTS="node"     BASE_PATH="."          TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
  - BUILD="mobile" EXPORTS="node"     BASE_PATH="."          TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
  - BUILD="compat" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
  - BUILD="legacy" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
  - BUILD="mobile" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
  - BUILD="modern" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" TEST_COMMAND="node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $BUILD != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $BUILD != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $BUILD != false ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=$EXPORTS -o $BASE_PATH/$BUILD || true"
  - $TEST_COMMAND
