language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - BASE_PATH="." EXPORTS="node" MAKE=false
  matrix:
    - BUILD="compat"
    - BUILD="modern"
    - BUILD="legacy" MAKE=true
    - BUILD="mobile" MAKE=true
    - BUILD="compat" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="legacy" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="mobile" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
    - BUILD="modern" EXPORTS="commonjs" BASE_PATH="./$EXPORTS" MAKE=true
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $MAKE != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=$EXPORTS -o $BASE_PATH/$BUILD || true"
  - "node ./node_modules/lodash/test/test.js $BASE_PATH/$BUILD/lodash.js"
