language: node_js
node_js:
  - "0.6"
  - "0.10"
env:
  - TEST_COMMAND="node ./node_modules/lodash/test/test.js ./compat/lodash.js"
  - TEST_COMMAND="node ./node_modules/lodash/test/test.js ./modern/lodash.js"
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash/"
  - $TEST_COMMAND
