language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - BUILD="compat" ISTANBUL=false
    - secure: "b4ZKDjezf7wDMt2VAtTAgeJWZBtPG0KTdGkvmpHpxTSx+f+S9K+DCK1W+wC6ApX1MCA6i9bw9fYtGeh4A21CTOPeBqhQ/oMkhqWLe5DxMhvj1s2yPMRnlbJtayuDgW5/PwTmEZ2AFHRZ2mBQ6vyCCkg9RsV37lrzm7ify53tzJY="
  matrix:
    - BUILD="compat"
    - BUILD="modern"
matrix:
  include:
    - node_js: "0.10"
      env: ISTANBUL=true BUILD="modern"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $ISTANBUL == false ]  || (npm i -g coveralls@\"~2.6.0\" && npm i istanbul@\"~0.2.0\")"
script:
  - "[ $ISTANBUL == false ] || (nvm use 0.11 && node --harmony ./node_modules/istanbul/lib/cli.js cover --report lcovonly ./node_modules/lodash/test/test.js -- ./modern/index.js)"
  - "[ $ISTANBUL == true ]  && (nvm use 0.10 && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage) || true"
  - "[ $ISTANBUL == true ]  || node ./node_modules/lodash/test/test.js ./$BUILD"
