language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - MAKE=false
  matrix:
    - BUILD="compat"
    - BUILD="modern"
    - BUILD="legacy"
    - BUILD="mobile"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $BUILD != 'compat' ] && [ $BUILD != 'modern' ] && MAKE=true || true"
  - "[ $MAKE != false ] && git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize $BUILD exports=node -o ./$BUILD || true"
script:
  - "node ./node_modules/lodash/test/test.js ./$BUILD"
